import React, {Component, Fragment as Frag} from 'react';
import TheMaze from "../../components/themaze";
import MainLayout from '../../layouts/main/Main';
import ModalComponent from '../../components/modal';
import "./style.css";

const boardConfig = [
    [
        {
            x: 0,
            y: 0,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 0,
            y: 1,
            isStart: true,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 0,
            y: 2,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 0,
            y: 3,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 0,
            y: 4,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 0,
            y: 5,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 0,
            y: 6,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 0,
            y: 7,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 0,
            y: 8,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 0,
            y: 9,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 0,
            y: 10,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 0,
            y: 11,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
    ],
    [
        {
            x: 1,
            y: 0,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 1,
            y: 1,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 1,
            y: 2,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 1,
            y: 3,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 1,
            y: 4,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 1,
            y: 5,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 1,
            y: 6,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 1,
            y: 7,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 1,
            y: 8,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 1,
            y: 9,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 1,
            y: 10,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 1,
            y: 11,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
    ],
    [
        {
            x: 2,
            y: 0,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 2,
            y: 1,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 2,
            y: 2,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 2,
            y: 3,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 2,
            y: 4,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 2,
            y: 5,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 2,
            y: 6,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 2,
            y: 7,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 2,
            y: 8,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 2,
            y: 9,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 2,
            y: 10,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 2,
            y: 11,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
    ],
    [
        {
            x: 3,
            y: 0,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 3,
            y: 1,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 3,
            y: 2,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 3,
            y: 3,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 3,
            y: 4,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 3,
            y: 5,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 3,
            y: 6,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 3,
            y: 7,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 3,
            y: 8,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 3,
            y: 9,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 3,
            y: 10,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 3,
            y: 11,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
    ],
    [
        {
            x: 4,
            y: 0,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 4,
            y: 1,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 4,
            y: 2,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 4,
            y: 3,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 4,
            y: 4,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 4,
            y: 5,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 4,
            y: 6,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 4,
            y: 7,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 4,
            y: 8,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 4,
            y: 9,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 4,
            y: 10,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 4,
            y: 11,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
    ],
    [
        {
            x: 5,
            y: 0,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 5,
            y: 1,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 5,
            y: 2,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 5,
            y: 3,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 5,
            y: 4,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 5,
            y: 5,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 5,
            y: 6,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 5,
            y: 7,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 5,
            y: 8,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 5,
            y: 9,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 5,
            y: 10,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 5,
            y: 11,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
    ],
    [
        {
            x: 6,
            y: 0,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 6,
            y: 1,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 6,
            y: 2,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 6,
            y: 3,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 6,
            y: 4,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 6,
            y: 5,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 6,
            y: 6,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 6,
            y: 6,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 6,
            y: 8,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 6,
            y: 9,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 6,
            y: 10,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 6,
            y: 11,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
    ],
    [
        {
            x: 7,
            y: 0,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 7,
            y: 1,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 7,
            y: 2,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 7,
            y: 3,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 7,
            y: 4,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 7,
            y: 5,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 7,
            y: 6,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 7,
            y: 7,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 7,
            y: 8,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 7,
            y: 9,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 7,
            y: 10,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 7,
            y: 11,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
    ],
    [
        {
            x: 8,
            y: 0,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 8,
            y: 1,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 8,
            y: 2,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 8,
            y: 3,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 8,
            y: 4,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 8,
            y: 5,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 8,
            y: 6,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 8,
            y: 7,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 8,
            y: 8,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 8,
            y: 9,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 8,
            y: 10,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 8,
            y: 11,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
    ],
    [
        {
            x: 9,
            y: 0,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 9,
            y: 1,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 9,
            y: 2,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 9,
            y: 3,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 9,
            y: 4,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 9,
            y: 5,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 9,
            y: 6,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 9,
            y: 7,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 9,
            y: 8,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 9,
            y: 9,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 9,
            y: 10,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 9,
            y: 11,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
    ],
    [
        {
            x: 10,
            y: 0,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 10,
            y: 1,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 10,
            y: 2,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 10,
            y: 3,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 10,
            y: 4,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 10,
            y: 5,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 10,
            y: 6,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 10,
            y: 7,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 10,
            y: 8,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 10,
            y: 9,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 10,
            y: 10,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
        {
            x: 10,
            y: 11,
            isStart: false,
            isFinish: true,
            distance: Infinity,
            isVisited: false,
            isWall: false,
            previousNode: null,
        },
    ],
    [
        {
            x: 11,
            y: 0,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 11,
            y: 1,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 11,
            y: 2,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 11,
            y: 3,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 11,
            y: 4,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 11,
            y: 5,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 11,
            y: 6,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 11,
            y: 7,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 11,
            y: 8,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 11,
            y: 9,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 11,
            y: 10,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
        {
            x: 11,
            y: 11,
            isStart: false,
            isFinish: false,
            distance: Infinity,
            isVisited: false,
            isWall: true,
            previousNode: null,
        },
    ],
];
const playerDefaultState = {
    x: 0,
    y: 1
};

class Home extends Component {
    constructor(props) {
        super(props);

        this.state = {
            speedAnimationResolve: 100,
            showModal: true
        };

        this.showModal = this.showModal.bind(this);
    }

    startResolveMaze () {
        document.getElementById("resolveMaze").click();
    }

    setSpeedAnimationResolve () {
        this.setState({
            ...this.state,
            speedAnimationResolve: 500,
        })
    }

    getNavTopOptions () {
        return  [
            {
                text: `Speed: ${this.state.speedAnimationResolve} ms`,
                onClick: () => {this.setSpeedAnimationResolve();}
            },
            {
                text: "Resolve",
                onClick: () => {this.startResolveMaze();}
            },
            {
                text: "Tutorial",
                onClick: () => {this.showModal()}
            },
            {
                text: "github",
                href: "https://github.com/werdnajoc/cookunity-themaze"
            }
        ];
    }

    showModal(e) {
        this.setState({
            ...this.state,
            showModal: !this.state.showModal
        });
    };

    render() {
        return (
            <MainLayout
                navTopOptions={this.getNavTopOptions()}
                title="Cookunity maze"
            >
                <div className="theMazeContainer" >
                    <TheMaze
                        resolve={this.state.resolveMaze}
                        startNode={boardConfig[0][1]}
                        finishNode={boardConfig[10][11]}
                        boardConfig={boardConfig}
                        playerDefaultState={playerDefaultState}
                        speedAnimationResolve={this.state.speedAnimationResolve}
                    />

                    <ModalComponent
                        close={this.showModal}
                        show={this.state.showModal}
                        title="Welcome to Cookunity maze"
                    />
                </div>
            </MainLayout>
        );
    }
}

export default Home
